#!/usr/bin/env bash
set -e

cd /var/www/skylark

gem install bundler -v '1.17.3'

bundle install --deployment --without test development -j4 && \
  find /var/www/skylark/vendor/bundle -name tmp -type d -exec rm -rf {} +

NODE_ENV=production yarn install

bundle clean
