defaults: &defaults
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>
  dbs:
    verify_code_service: 2
    model: 5
    sidekiq: 12
    cable: 14
    weixin_authorize: 15
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
