name: CI

on: [pull_request]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Run Parallel
        run: |
          ./images/arm-base/build
